### ISSUE TITLE
Feature Requests from digitalegarage

### ISSUE THREAD

**Issue by Elyytscha** [quizlet/argocd-diff-action#60]
Hello, as you may have noticed or not, we forked your repo, as we needed some features: https://github.com/digitalegarage/argocd-diff-action?tab=readme-ov-file#config-we-added

It would be really awesome if we could implement this features (without breaking your actual needed behaviour of the action) upstream, the following features can be implemented like we did imo, as we have taken care to no break your actual logic. Also we didn't changed your defaults.

```yaml
          # Allows to customize if the Diff should be collapsed in the github comment
          collapse-diff: false
          # Sets Timezone
          timezone: America/Los_Angeles
          # Sets Presentation of the date
          timezone-locale: en-US
          # sets the diff tool which will be used in the argocd diff command
          diff-tool: diff -N -u
```

the feature which enables:
tracking-label: argocd.argoproj.io/instance 
in actual state may be a breaking change, this would need some rework i think. basically this logic.
![image](https://github.com/user-attachments/assets/ca7f8e81-60c0-4a05-930e-ebb26c685b4f)
